#!/usr/bin/env bash
# install nginx to create html pages
sudo apt-get -y update
sudo apt-get -y install nginx
# Changing to sudo for update the file
echo "Holberton School" > /var/www/html/index.html
sudo service nginx start
