#!/usr/bin/env bash
# install nginx to create html pages
sudo apt-get -y update
sudo apt-get -y install nginx
# Changing to sudo for update the file
echo "Holberton School" > /var/www/html/index.html
sudo service nginx start
#the default file that has the location will be modified
#in addition to giving it the path to find it
string_to_replace="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
src="/etc/nginx/sites-available/default"
sudo sed -i "30i $string_to_replace" $src
sudo service nginx reload
sudo service nginx restart