#!/usr/bin/env bash
# Fix container 
netstat -lpn | grep apache | awk -F' ' '{print $7}' | cut -d'/' -f1 | xargs kill
chown -R nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80 default/8080 default/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
